import React from "react";
import {
  Clock,
  CheckCircle2,
  MessageCircle,
  Mail,
  User,
  Smile,
  Paperclip,
  Download,
  X,
  Zap,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  MapPin,
  Play,
} from "lucide-react";
// import { useAuth } from "../../../app/providers/AuthProvider";
// import { FK } from "../../../capabilities/featureKeys";

import { useAuth } from "../../../app/providers/AuthProvider";
import { FK } from "../../../capabilities/featureKeys";
import { StatusIcon } from "./shared/StatusIcon";
import { ComposerTabs } from "./ComposerTabs";
import EmojiPicker from "./EmojiPicker";
import { formatDateTime, getInitial } from "../utils/formatters";

const formatBytes = bytes => {
  const n = Number(bytes);
  if (!Number.isFinite(n) || n <= 0) return null;
  const units = ["B", "KB", "MB", "GB"];
  let value = n;
  let i = 0;
  while (value >= 1024 && i < units.length - 1) {
    value /= 1024;
    i += 1;
  }
  const fixed = value >= 100 ? 0 : value >= 10 ? 1 : 2;
  return `${value.toFixed(fixed)} ${units[i]}`;
};

const resolveChatMediaType = msg => {
  const explicit = String(msg?.mediaType ?? msg?.MediaType ?? "")
    .trim()
    .toLowerCase();

  const mime = String(msg?.mimeType ?? msg?.MimeType ?? "")
    .split(";")[0]
    .trim()
    .toLowerCase();

  const fileName = String(msg?.fileName ?? msg?.FileName ?? "")
    .trim()
    .toLowerCase();

  if (explicit === "location") return "location";

  if (mime) {
    if (mime === "application/pdf") return "document";
    if (mime.startsWith("image/")) return "image";
    if (mime.startsWith("video/")) return "video";
    if (mime.startsWith("audio/")) return "audio";
  }

  if (fileName) {
    if (fileName.endsWith(".pdf")) return "document";
    if (
      fileName.endsWith(".mp4") ||
      fileName.endsWith(".3gp") ||
      fileName.endsWith(".3gpp") ||
      fileName.endsWith(".webm") ||
      fileName.endsWith(".mov")
    ) {
      return "video";
    }
    if (
      fileName.endsWith(".mp3") ||
      fileName.endsWith(".m4a") ||
      fileName.endsWith(".aac") ||
      fileName.endsWith(".ogg") ||
      fileName.endsWith(".wav")
    ) {
      return "audio";
    }
  }

  return explicit;
};

const formatTimeShort = sentAt => {
  if (!sentAt) return null;
  try {
    return new Date(sentAt).toLocaleTimeString([], {
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return null;
  }
};

const looksLikeAutoGeneratedMediaText = ({ text, mediaType, fileName }) => {
  const raw = String(text || "").trim();
  if (!raw) return false;

  const mt = String(mediaType || "")
    .trim()
    .toLowerCase();
  const name = String(fileName || "")
    .trim()
    .toLowerCase();

  const norm = raw
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();

  if (name && norm === name) return true;

  if (mt === "image") {
    if (norm === "photo" || norm === "image") return true;
    if (norm.startsWith("image sent")) return true;
    if (norm.startsWith("photo sent")) return true;
    return false;
  }

  if (mt === "document") {
    if (norm === "pdf" || norm === "document") return true;
    if (norm.startsWith("pdf sent")) return true;
    if (norm.startsWith("document sent")) return true;
    return false;
  }

  if (mt === "video") {
    if (norm === "video") return true;
    if (norm.startsWith("video sent")) return true;
    return false;
  }

  if (mt === "audio") {
    if (norm === "audio") return true;
    if (norm.startsWith("audio sent")) return true;
    return false;
  }

  if (mt === "location") {
    if (norm === "location") return true;
    if (norm.startsWith("location sent")) return true;
    return false;
  }

  return false;
};

function TimeStatusOverlay({ timeText, showStatus, status, className }) {
  if (!timeText) return null;

  return (
    <div className={className}>
      <span>{timeText}</span>
      {showStatus && <StatusIcon status={status} variant="onDark" />}
    </div>
  );
}

function PdfMediaCard({
  msg,
  isInbound,
  pdfMeta,
  onOpen,
  ensurePdfPreview,
}) {
  const mediaId = String(msg?.mediaId || "").trim();

  React.useEffect(() => {
    if (!mediaId) return;
    ensurePdfPreview?.(mediaId);
  }, [mediaId, ensurePdfPreview]);

  const fileName = String(msg?.fileName || "").trim() || "Document.pdf";
  const pages =
    typeof pdfMeta?.pages === "number" && pdfMeta.pages > 0 ? pdfMeta.pages : null;
  const sizeLabel = formatBytes(pdfMeta?.sizeBytes);

  const metaLine = [
    "PDF",
    pages ? `${pages} pages` : null,
    sizeLabel || null,
  ]
    .filter(Boolean)
    .join(" · ");

  return (
    <button
      type="button"
      onClick={() => onOpen?.(msg)}
      className={`relative w-[320px] max-w-full text-left rounded-lg overflow-hidden border ${
        isInbound
          ? "bg-slate-50 border-slate-200"
          : "bg-black/15 border-black/10"
      }`}
      title="Open PDF"
    >
      <div className="flex items-stretch">
        <div className="w-[88px] h-[64px] bg-black/10 flex items-center justify-center overflow-hidden">
          {pdfMeta?.thumbDataUrl ? (
            <img
              src={pdfMeta.thumbDataUrl}
              alt="PDF preview"
              className="w-full h-full object-cover"
              loading="lazy"
            />
          ) : (
            <div className="flex items-center gap-2 text-[12px] font-semibold">
              <span className="inline-flex items-center justify-center w-8 h-8 rounded bg-rose-600 text-white text-[11px]">
                PDF
              </span>
            </div>
          )}
        </div>

        <div className="flex-1 px-3 py-2 min-w-0">
          <div className="text-[13px] font-semibold truncate">{fileName}</div>
          <div className={`text-[11px] mt-0.5 ${isInbound ? "text-slate-500" : "text-white/80"}`}>
            {metaLine}
          </div>
        </div>

        <div className="px-3 py-2 flex items-center">
          <div
            className={`w-8 h-8 rounded-full flex items-center justify-center ${
              isInbound ? "bg-slate-200 text-slate-700" : "bg-black/20 text-white"
            }`}
          >
            <Download className="w-4 h-4" />
          </div>
        </div>
      </div>
    </button>
  );
}

function ImageMediaTile({
  msg,
  isInbound,
  previewUrl,
  onOpen,
  ensureImagePreview,
  timeText,
  status,
  showStatus,
}) {
  const mediaId = String(msg?.mediaId || "").trim();

  React.useEffect(() => {
    if (!mediaId) return;
    if (previewUrl) return;
    ensureImagePreview?.(mediaId);
  }, [mediaId, previewUrl, ensureImagePreview]);

  return (
    <button
      type="button"
      onClick={() => onOpen?.(msg)}
      className="relative block w-[240px] max-w-full aspect-[4/3] rounded-lg overflow-hidden border border-black/10"
      title="Open image"
    >
      {previewUrl ? (
        <img
          src={previewUrl}
          alt={msg?.fileName || "Image"}
          className="absolute inset-0 w-full h-full object-cover"
          loading="lazy"
        />
      ) : (
        <div
          className={`absolute inset-0 ${
            isInbound ? "bg-slate-200/70" : "bg-black/15"
          }`}
        />
      )}

      {!previewUrl && (
        <div className="absolute inset-0 flex items-center justify-center">
          <div
            className={`w-10 h-10 rounded-full flex items-center justify-center ${
              isInbound ? "bg-white/80 text-slate-700" : "bg-black/30 text-white"
            }`}
          >
            <Download className="w-5 h-5" />
          </div>
        </div>
      )}

      <TimeStatusOverlay
        timeText={timeText}
        showStatus={showStatus}
        status={status}
        className="absolute bottom-1 right-1 px-1.5 py-[1px] rounded bg-black/45 text-white text-[10px] leading-none flex items-center gap-0.5"
      />
    </button>
  );
}

function VideoMediaTile({
  msg,
  isInbound,
  previewUrl,
  onOpen,
  ensureMediaPreview,
  timeText,
  status,
  showStatus,
}) {
  const mediaId = String(msg?.mediaId || "").trim();

  React.useEffect(() => {
    if (!mediaId) return;
    if (previewUrl) return;
    ensureMediaPreview?.(mediaId);
  }, [mediaId, previewUrl, ensureMediaPreview]);

  return (
    <button
      type="button"
      onClick={() => onOpen?.(msg)}
      className="relative block w-[240px] max-w-full aspect-[4/3] rounded-lg overflow-hidden border border-black/10"
      title="Open video"
    >
      {previewUrl ? (
        <video
          src={previewUrl}
          className="absolute inset-0 w-full h-full object-cover"
          muted
          playsInline
          preload="metadata"
        />
      ) : (
        <div
          className={`absolute inset-0 ${
            isInbound ? "bg-slate-200/70" : "bg-black/15"
          }`}
        />
      )}

      <div className="absolute inset-0 flex items-center justify-center">
        <div
          className={`w-12 h-12 rounded-full flex items-center justify-center ${
            isInbound ? "bg-white/80 text-slate-700" : "bg-black/30 text-white"
          }`}
        >
          <Play className="w-6 h-6" />
        </div>
      </div>

      {!previewUrl && (
        <div className="absolute left-3 bottom-3 w-8 h-8 rounded-full bg-black/30 text-white flex items-center justify-center">
          <Download className="w-4 h-4" />
        </div>
      )}

      <TimeStatusOverlay
        timeText={timeText}
        showStatus={showStatus}
        status={status}
        className="absolute bottom-1 right-1 px-1.5 py-[1px] rounded bg-black/45 text-white text-[10px] leading-none flex items-center gap-0.5"
      />
    </button>
  );
}

function AudioMediaCard({ msg, isInbound, previewUrl, ensureMediaPreview }) {
  const mediaId = String(msg?.mediaId || "").trim();

  React.useEffect(() => {
    if (!mediaId) return;
    if (previewUrl) return;
    ensureMediaPreview?.(mediaId);
  }, [mediaId, previewUrl, ensureMediaPreview]);

  const fileName = String(msg?.fileName || "").trim() || "Audio";

  return (
    <div
      className={`w-[320px] max-w-full rounded-lg border overflow-hidden ${
        isInbound ? "bg-slate-50 border-slate-200" : "bg-black/15 border-black/10"
      }`}
    >
      <div className="px-3 py-2">
        <div className="text-[13px] font-semibold truncate">{fileName}</div>
        <div className="mt-2">
          {previewUrl ? (
            <audio
              controls
              src={previewUrl}
              className="w-full"
              preload="metadata"
            />
          ) : (
            <div className="h-10 flex items-center justify-between px-3 rounded bg-black/10">
              <span className={`text-[12px] ${isInbound ? "text-slate-500" : "text-white/80"}`}>
                Loading audio...
              </span>
              <Download className={`w-4 h-4 ${isInbound ? "text-slate-600" : "text-white"}`} />
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function LocationCard({ msg, isInbound }) {
  const lat =
    msg?.locationLatitude ??
    msg?.LocationLatitude ??
    msg?.latitude ??
    null;
  const lon =
    msg?.locationLongitude ??
    msg?.LocationLongitude ??
    msg?.longitude ??
    null;
  const name = String(
    msg?.locationName ?? msg?.LocationName ?? msg?.name ?? ""
  ).trim();
  const address = String(
    msg?.locationAddress ?? msg?.LocationAddress ?? msg?.address ?? ""
  ).trim();

  const hasCoords = Number.isFinite(Number(lat)) && Number.isFinite(Number(lon));
  const mapsUrl = hasCoords
    ? `https://www.google.com/maps?q=${encodeURIComponent(
        `${Number(lat)},${Number(lon)}`
      )}`
    : null;

  return (
    <a
      href={mapsUrl || "#"}
      target={mapsUrl ? "_blank" : undefined}
      rel={mapsUrl ? "noreferrer noopener" : undefined}
      onClick={e => {
        if (!mapsUrl) e.preventDefault();
      }}
      className={`block w-[320px] max-w-full rounded-lg border overflow-hidden ${
        isInbound ? "bg-slate-50 border-slate-200" : "bg-black/15 border-black/10"
      }`}
      title={mapsUrl ? "Open in Google Maps" : "Location"}
    >
      <div className="flex items-center gap-3 px-3 py-3">
        <div
          className={`w-10 h-10 rounded-full flex items-center justify-center ${
            isInbound ? "bg-slate-200 text-slate-700" : "bg-black/25 text-white"
          }`}
        >
          <MapPin className="w-5 h-5" />
        </div>
        <div className="min-w-0">
          <div className="text-[13px] font-semibold truncate">
            {name || "Location"}
          </div>
          {address ? (
            <div className={`text-[11px] mt-0.5 truncate ${isInbound ? "text-slate-500" : "text-white/80"}`}>
              {address}
            </div>
          ) : hasCoords ? (
            <div className={`text-[11px] mt-0.5 ${isInbound ? "text-slate-500" : "text-white/80"}`}>
              {Number(lat).toFixed(5)}, {Number(lon).toFixed(5)}
            </div>
          ) : null}
        </div>
      </div>
    </a>
  );
}

function MediaViewerModal({
  viewer,
  onClose,
  onPrev,
  onNext,
  onSelectIndex,
  mediaObjectUrlById,
  ensureImagePreview,
}) {
  const open = Boolean(viewer?.open);
  const url = viewer?.url;
  const type = viewer?.type;
  const loading = Boolean(viewer?.loading);
  const items = Array.isArray(viewer?.items) ? viewer.items : [];
  const index =
    Number.isFinite(Number(viewer?.index)) && Number(viewer?.index) >= 0
      ? Number(viewer.index)
      : 0;
  const canPrev = type === "image" && items.length > 1 && index > 0;
  const canNext =
    type === "image" && items.length > 1 && index < items.length - 1;

  React.useEffect(() => {
    if (!open) return;
    const onKeyDown = e => {
      if (e.key === "Escape") onClose?.();
      if (e.key === "ArrowLeft" && canPrev) onPrev?.();
      if (e.key === "ArrowRight" && canNext) onNext?.();
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [open, onClose, onPrev, onNext, canPrev, canNext]);

  React.useEffect(() => {
    if (!open) return;
    const prev = document?.body?.style?.overflow;
    if (document?.body?.style) document.body.style.overflow = "hidden";
    return () => {
      if (document?.body?.style) document.body.style.overflow = prev || "";
    };
  }, [open]);

  if (!open || !url) return null;

  return (
    <div
      className="fixed inset-0 z-[9999] bg-black/80 flex items-center justify-center p-4"
      role="dialog"
      aria-modal="true"
      onClick={() => onClose?.()}
    >
      {type === "image" && (
        <>
          <button
            type="button"
            onClick={e => {
              e.stopPropagation();
              if (canPrev) onPrev?.();
            }}
            className={`absolute left-4 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-black/50 text-white flex items-center justify-center hover:bg-black/70 ${
              canPrev ? "" : "opacity-40 cursor-not-allowed"
            }`}
            aria-label="Previous image"
            disabled={!canPrev}
          >
            <ChevronLeft className="w-6 h-6" />
          </button>

          <button
            type="button"
            onClick={e => {
              e.stopPropagation();
              if (canNext) onNext?.();
            }}
            className={`absolute right-4 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-black/50 text-white flex items-center justify-center hover:bg-black/70 ${
              canNext ? "" : "opacity-40 cursor-not-allowed"
            }`}
            aria-label="Next image"
            disabled={!canNext}
          >
            <ChevronRight className="w-6 h-6" />
          </button>
        </>
      )}

      <button
        type="button"
        onClick={() => onClose?.()}
        className="absolute top-4 right-4 w-10 h-10 rounded-full bg-black/50 text-white flex items-center justify-center hover:bg-black/70"
        aria-label="Close"
      >
        <X className="w-5 h-5" />
      </button>

      <div
        className="max-w-[92vw] max-h-[92vh]"
        onClick={e => e.stopPropagation()}
      >
        {type === "image" ? (
          <div className="relative">
            <img
              src={url}
              alt={viewer?.fileName || "Image"}
              className="max-w-[92vw] max-h-[92vh] object-contain rounded-lg"
            />

            {loading && (
              <div className="absolute inset-0 bg-black/40 flex items-center justify-center rounded-lg">
                <div className="w-12 h-12 rounded-full bg-black/40 flex items-center justify-center">
                  <Download className="w-6 h-6 text-white" />
                </div>
              </div>
            )}
          </div>
        ) : type === "video" ? (
          <video
            src={url}
            controls
            autoPlay
            playsInline
            className="max-w-[92vw] max-h-[92vh] object-contain rounded-lg bg-black"
          />
        ) : null}
      </div>

      {type === "image" && items.length > 1 && (
        <div
          className="absolute left-1/2 -translate-x-1/2 bottom-4 w-[min(900px,92vw)]"
          onClick={e => e.stopPropagation()}
        >
          <div className="px-2 py-2 rounded-xl bg-black/45">
            <div className="flex gap-2 overflow-x-auto">
              {items.map((it, i) => {
                const id = String(it?.mediaId || "").trim();
                if (!id) return null;
                const thumb =
                  mediaObjectUrlById?.[id] || (i === index ? url : null);
                const active = i === index;

                return (
                  <button
                    key={id}
                    type="button"
                    className={`relative shrink-0 w-[64px] h-[44px] rounded-md overflow-hidden border ${
                      active
                        ? "border-white"
                        : "border-white/20 hover:border-white/40"
                    }`}
                    onMouseEnter={() => ensureImagePreview?.(id)}
                    onClick={() => onSelectIndex?.(i)}
                    title={it?.fileName || "Image"}
                  >
                    {thumb ? (
                      <img
                        src={thumb}
                        alt="thumbnail"
                        className="w-full h-full object-cover"
                        loading="lazy"
                      />
                    ) : (
                      <div className="w-full h-full bg-white/10 flex items-center justify-center">
                        <Download className="w-4 h-4 text-white/70" />
                      </div>
                    )}
                  </button>
                );
              })}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export function MiddlePanel({
  selectedConversation,
  messages,
  mediaObjectUrlById,
  pdfPreviewById,
  mediaViewer,
  handleMediaViewerPrev,
  handleMediaViewerNext,
  handleMediaViewerSelectIndex,
  messagesEndRef,
  messagesWithSeparators,
  messagesHasMore,
  newMessage,
  setNewMessage,
  isSending,
  isUploadingMedia,
  handleSendMessage,
  handleUploadAndSendMedia,
  handleSendLocation,
  handleOpenMedia,
  handleCloseMediaViewer,
  ensureImagePreview,
  ensurePdfPreview,
  handleComposerKeyDown,
  headerIsAssigned,
  headerIsAssignedToMe,
  headerAssignedName,
  isWithin24h,
  normalizedStatus,
  statusPillClass,
  agents,
  isAgentsLoading,
  currentUserId,
  isAssigning,
  handleAssignToMe,
  handleAssignToAgent,
  handleUnassign,
  isUpdatingStatus,
  handleUpdateConversationStatus,
  isMessagesLoading,
  isMessagesLoadingOlder,
  onLoadOlderMessages,
  isConversationClosed,
  showRightPanel,
  setShowRightPanel,
  assigneeMenuOpen,
  setAssigneeMenuOpen,
  statusMenuOpen,
  setStatusMenuOpen,
}) {
  const messagesScrollRef = React.useRef(null);
  const composerRef = React.useRef(null);
  const [openTab, setOpenTab] = React.useState(null);
  const [emojiOpen, setEmojiOpen] = React.useState(false);
  const textareaRef = React.useRef(null);
  const fileInputRef = React.useRef(null);

  const { hasAllAccess, role, can } = useAuth() || {};
  const roleLower = String(role || "").toLowerCase();
  const isPrivilegedRole =
    ["admin", "superadmin", "business", "partner"].includes(roleLower) ||
    Boolean(hasAllAccess);
  const canAssignOthers = Boolean(
    isPrivilegedRole || (typeof can === "function" && can(FK.INBOX_CHAT_ASSIGN))
  );

  // const otherAgents = React.useMemo(() => {
  //   return (agents ?? []).filter(a =>
  //     currentUserId ? String(a.userId) !== String(currentUserId) : true
  //   );
  // }, [agents, currentUserId]);
  const otherAgents = React.useMemo(() => {
    const list = agents ?? [];

    const isBusinessOwner = a => {
      // Prefer an explicit flag if your API provides it
      const flag =
        a?.isBusinessOwner ??
        a?.IsBusinessOwner ??
        a?.isOwner ??
        a?.IsOwner ??
        false;

      if (flag) return true;

      // Fallback to roleName/roleCode (your agents mapper includes roleName)
      const role = String(a?.roleName ?? a?.roleCode ?? a?.role ?? "")
        .toLowerCase()
        .trim();
      return (
        role === "business" ||
        role === "businessowner" ||
        role === "business owner" ||
        role === "owner"
      );
    };

    return list
      .filter(a =>
        currentUserId ? String(a.userId) !== String(currentUserId) : true
      )
      .filter(a => !isBusinessOwner(a));
  }, [agents, currentUserId]);

  const handleLoadOlderMessages = React.useCallback(async () => {
    const el = messagesScrollRef.current;
    if (!el || typeof onLoadOlderMessages !== "function") {
      await onLoadOlderMessages?.();
      return;
    }

    const prevScrollHeight = el.scrollHeight;
    const prevScrollTop = el.scrollTop;

    await onLoadOlderMessages();

    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        const current = messagesScrollRef.current;
        if (!current) return;
        const newScrollHeight = current.scrollHeight;
        current.scrollTop =
          prevScrollTop + (newScrollHeight - prevScrollHeight);
      });
    });
  }, [onLoadOlderMessages]);

  const isComposerDisabled =
    !selectedConversation ||
    isConversationClosed ||
    !isWithin24h ||
    isSending ||
    isUploadingMedia;

  const insertAtCursor = React.useCallback(
    snippet => {
      const el = textareaRef.current;
      if (!el) {
        setNewMessage(prev => (prev ? `${prev}${snippet}` : snippet));
        return;
      }
      const start = el.selectionStart ?? (newMessage?.length ?? 0);
      const end = el.selectionEnd ?? (newMessage?.length ?? 0);
      const base = newMessage ?? "";
      const next = base.slice(0, start) + snippet + base.slice(end);
      setNewMessage(next);
      requestAnimationFrame(() => {
        el.focus();
        const pos = start + snippet.length;
        el.setSelectionRange(pos, pos);
      });
    },
    [newMessage, setNewMessage]
  );

  const handleTextareaKeyDown = e => {
    if (e.key === "Escape" && emojiOpen) {
      e.preventDefault();
      e.stopPropagation();
      setEmojiOpen(false);
      return;
    }

    if (
      !isComposerDisabled &&
      e.key === "/" &&
      !e.shiftKey &&
      !e.altKey &&
      !e.ctrlKey &&
      !e.metaKey
    ) {
      const msg = newMessage ?? "";
      const start = e.currentTarget?.selectionStart ?? msg.length;
      const end = e.currentTarget?.selectionEnd ?? msg.length;
      const cursorAtStart = start === 0 && end === 0;
      const messageEmpty = msg.length === 0;

      if (messageEmpty || cursorAtStart) {
        e.preventDefault();
        setEmojiOpen(false);
        setOpenTab("quickReply");
        return;
      }
    }

    handleComposerKeyDown?.(e);
  };

  return (
    <div className="flex-1 flex flex-col">
      <MediaViewerModal
        viewer={mediaViewer}
        onClose={handleCloseMediaViewer}
        onPrev={handleMediaViewerPrev}
        onNext={handleMediaViewerNext}
        onSelectIndex={handleMediaViewerSelectIndex}
        mediaObjectUrlById={mediaObjectUrlById}
        ensureImagePreview={ensureImagePreview}
      />
      <div className="h-[64px] border-b border-slate-200 bg-white flex items-center justify-between px-4">
        {selectedConversation ? (
          <>
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-full bg-emerald-100 flex items-center justify-center text-xs font-semibold text-emerald-700">
                {getInitial(
                  selectedConversation.contactName,
                  selectedConversation.contactPhone
                )}
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-sm font-semibold text-slate-800">
                    {selectedConversation.contactName ||
                      selectedConversation.contactPhone}
                  </span>
                  <span className="text-[11px] text-slate-400">
                    {selectedConversation.contactPhone}
                  </span>
                </div>
                <div className="flex items-center gap-3 text-[11px] text-slate-400 mt-0.5">
                  <span className="flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    {selectedConversation.lastInboundAt
                      ? formatDateTime(selectedConversation.lastInboundAt)
                      : "Last inbound: -"}
                  </span>
                  <span
                    className={`inline-flex items-center gap-1 px-2 py-[1px] rounded-full text-[10px] border ${
                      isWithin24h
                        ? "bg-emerald-50 text-emerald-700 border-emerald-200"
                        : "bg-rose-50 text-rose-700 border-rose-200"
                    }`}
                  >
                    <Clock className="w-3 h-3" />
                    {isWithin24h ? "Within 24h" : "Outside 24h"}
                  </span>
                </div>
              </div>
            </div>

            <div className="flex items-center gap-2 text-[11px] text-slate-500">
              <span className="flex items-center gap-1">
                <MessageCircle className="w-3 h-3" />
                {selectedConversation.sourceName || "WhatsApp"}
              </span>
              <span className="flex items-center gap-1">
                <Mail className="w-3 h-3" />
                {selectedConversation.mode || "Live"}
              </span>

              <div className="relative ml-2">
                <button
                  type="button"
                  aria-label="Assignee"
                  onClick={() => {
                    setStatusMenuOpen(false);
                    setAssigneeMenuOpen(v => !v);
                  }}
                  disabled={isAssigning}
                  className={`inline-flex items-center gap-1 rounded-full border bg-white px-3 py-[3px] text-[11px] ${
                    isAssigning
                      ? "border-slate-200 text-slate-400 cursor-wait"
                      : "border-slate-200 text-slate-700 hover:bg-slate-50"
                  }`}
                >
                  <User className="w-3 h-3" />
                  {headerIsAssigned
                    ? headerIsAssignedToMe
                      ? "You"
                      : headerAssignedName || "Agent"
                    : "Unassigned"}
                  <ChevronDown className="w-3 h-3" />
                </button>

                {assigneeMenuOpen && (
                  <>
                    <button
                      type="button"
                      aria-label="Close assignee menu"
                      className="fixed inset-0 z-10 cursor-default"
                      onClick={() => setAssigneeMenuOpen(false)}
                    />
                    <div className="absolute right-0 mt-2 w-64 rounded-xl border border-slate-200 bg-white shadow-lg overflow-hidden z-20">
                      <div className="px-3 py-2 text-[10px] text-slate-500 border-b border-slate-100">
                        Agent List
                      </div>

                      <button
                        type="button"
                        className="w-full text-left px-3 py-2 text-[11px] text-slate-700 hover:bg-slate-50 disabled:opacity-50"
                        onClick={() => {
                          setAssigneeMenuOpen(false);
                          handleAssignToMe();
                        }}
                        disabled={!currentUserId || headerIsAssignedToMe}
                      >
                        Assign to me
                      </button>

                      <div className="max-h-56 overflow-y-auto">
                        {canAssignOthers ? (
                          <>
                            {isAgentsLoading && (
                              <div className="px-3 py-2 text-[11px] text-slate-400">
                                Loading agents...
                              </div>
                            )}

                            {!isAgentsLoading &&
                              otherAgents.map(a => (
                                <button
                                  key={a.userId}
                                  type="button"
                                  className="w-full text-left px-3 py-2 text-[11px] text-slate-700 hover:bg-slate-50"
                                  onClick={() => {
                                    setAssigneeMenuOpen(false);
                                    handleAssignToAgent(a.userId);
                                  }}
                                >
                                  Assign to {a.name}
                                  {a.roleName ? (
                                    <span className="ml-1 text-[10px] text-slate-400">
                                      ({a.roleName})
                                    </span>
                                  ) : null}
                                </button>
                              ))}

                            {!isAgentsLoading && otherAgents.length === 0 && (
                              <div className="px-3 py-2 text-[11px] text-slate-400">
                                No other agents found.
                              </div>
                            )}
                          </>
                        ) : (
                          <div className="px-3 py-2 text-[11px] text-slate-500">
                            You can only assign to yourself. Ask an admin to
                            reassign.
                          </div>
                        )}
                      </div>

                      {headerIsAssigned &&
                        (headerIsAssignedToMe || canAssignOthers) && (
                          <button
                            type="button"
                            className="w-full text-left px-3 py-2 text-[11px] text-rose-700 hover:bg-rose-50 border-t border-slate-100 disabled:opacity-50"
                            onClick={() => {
                              setAssigneeMenuOpen(false);
                              handleUnassign();
                            }}
                            disabled={isAssigning}
                          >
                            Unassign
                          </button>
                        )}
                    </div>
                  </>
                )}
              </div>

              <div className="relative">
                <button
                  type="button"
                  aria-label="Status"
                  onClick={() => {
                    if (!headerIsAssignedToMe) return;
                    setAssigneeMenuOpen(false);
                    setStatusMenuOpen(v => !v);
                  }}
                  disabled={!headerIsAssignedToMe || isUpdatingStatus}
                  title={
                    headerIsAssignedToMe
                      ? "Update status"
                      : "Assign to yourself to update status"
                  }
                  className={`inline-flex items-center gap-1 rounded-full border px-3 py-[3px] text-[11px] ${
                    !headerIsAssignedToMe || isUpdatingStatus
                      ? "bg-slate-50 text-slate-400 border-slate-200 cursor-not-allowed"
                      : `${statusPillClass} hover:opacity-90`
                  }`}
                >
                  <CheckCircle2 className="w-3 h-3" />
                  {normalizedStatus}
                  <ChevronDown className="w-3 h-3" />
                </button>

                {statusMenuOpen && headerIsAssignedToMe && (
                  <>
                    <button
                      type="button"
                      aria-label="Close status menu"
                      className="fixed inset-0 z-10 cursor-default"
                      onClick={() => setStatusMenuOpen(false)}
                    />
                    <div className="absolute right-0 mt-2 w-40 rounded-xl border border-slate-200 bg-white shadow-lg overflow-hidden z-20">
                      {["Open", "Pending", "Closed"].map(s => (
                        <button
                          key={s}
                          type="button"
                          className={`w-full text-left px-3 py-2 text-[11px] hover:bg-slate-50 ${
                            s === "Closed"
                              ? "text-rose-700"
                              : s === "Pending"
                              ? "text-amber-700"
                              : "text-emerald-700"
                          }`}
                          onClick={() => {
                            setStatusMenuOpen(false);
                            handleUpdateConversationStatus(s);
                          }}
                        >
                          {s}
                        </button>
                      ))}
                    </div>
                  </>
                )}
              </div>

              <button
                type="button"
                onClick={() => setShowRightPanel(v => !v)}
                aria-label={
                  showRightPanel ? "Hide details panel" : "Show details panel"
                }
                title={showRightPanel ? "Hide details" : "Show details"}
                className="ml-2 inline-flex h-8 w-8 items-center justify-center rounded-full border border-transparent text-emerald-600 hover:bg-slate-50 hover:text-emerald-700"
              >
                {showRightPanel ? (
                  <ChevronRight className="h-4 w-4" />
                ) : (
                  <ChevronLeft className="h-4 w-4" />
                )}
              </button>
            </div>
          </>
        ) : (
          <div className="text-xs text-slate-400">
            Select a conversation to start chatting.
          </div>
        )}
      </div>

      <div
        ref={messagesScrollRef}
        className="flex-1 overflow-y-auto bg-slate-50 px-4 py-3"
      >
        {!selectedConversation && (
          <div className="h-full flex items-center justify-center text-xs text-slate-400">
            No conversation selected.
          </div>
        )}

        {selectedConversation && (
          <div className="flex flex-col gap-2 text-xs">
            {messagesHasMore && (
              <div className="flex justify-center">
                <button
                  type="button"
                  onClick={handleLoadOlderMessages}
                  disabled={isMessagesLoadingOlder}
                  className={`rounded-full border px-3 py-1 text-[11px] font-medium ${
                    isMessagesLoadingOlder
                      ? "bg-slate-100 text-slate-400 border-slate-200 cursor-wait"
                      : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
                  }`}
                >
                  {isMessagesLoadingOlder
                    ? "Loading older..."
                    : "Load older messages"}
                </button>
              </div>
            )}

            {isMessagesLoading && (
              <div className="text-slate-400">Loading messages...</div>
            )}

            {!isMessagesLoading && messages.length === 0 && (
              <div className="text-slate-400 italic">
                No messages yet for this contact.
              </div>
            )}

            {!isMessagesLoading &&
              messagesWithSeparators.length > 0 &&
              messagesWithSeparators.map(item => {
                if (item.type === "separator") {
                  return (
                    <div key={item.id} className="flex justify-center my-2">
                      <span className="px-3 py-0.5 rounded-full bg-slate-100 text-[10px] text-slate-500">
                        {item.label}
                      </span>
                    </div>
                  );
                }

                const msg = item;
                const isInbound = !!msg.isInbound;
                const mediaId = String(msg.mediaId ?? msg.MediaId ?? "").trim();
                const mtOuter = resolveChatMediaType(msg);
                const hasMedia =
                  mtOuter === "location" ||
                  (Boolean(mediaId) &&
                    (mtOuter === "image" ||
                      mtOuter === "document" ||
                      mtOuter === "video" ||
                      mtOuter === "audio"));
                const timeText = formatTimeShort(msg.sentAt);
                const showStatus = !msg.isInbound;
                const fileName = msg.fileName ?? msg.FileName ?? "";
                const rawText = String(msg.text || "").trim();
                const showCaption = hasMedia
                  ? mtOuter === "location"
                    ? false
                    : rawText &&
                      !looksLikeAutoGeneratedMediaText({
                        text: rawText,
                        mediaType: mtOuter,
                        fileName,
                      })
                  : true;
                const captionText =
                  hasMedia && showCaption && rawText ? msg.text : null;
                const showBottomMeta =
                  !hasMedia ||
                  mtOuter === "document" ||
                  mtOuter === "audio" ||
                  mtOuter === "location" ||
                  ((mtOuter === "image" || mtOuter === "video") &&
                    Boolean(captionText));
                const bubblePadding = hasMedia
                  ? showBottomMeta
                    ? "p-2 pb-4"
                    : "p-2"
                  : "px-3 py-2 pb-4";
                const contentRightPad = showBottomMeta
                  ? isInbound
                    ? "pr-8"
                    : "pr-12"
                  : "pr-0";
                const key = String(
                  msg.id ??
                    msg.messageLogId ??
                    msg.serverId ??
                    msg.messageId ??
                    msg.providerMessageId ??
                    msg.clientMessageId ??
                    `${msg.sentAt ?? "unknown"}-${
                      isInbound ? "in" : "out"
                    }-${String(msg.text ?? "").slice(0, 32)}`
                );

                return (
                  <div
                    key={key}
                    className={`flex ${
                      isInbound ? "justify-start" : "justify-end"
                    }`}
                  >
                    <div
                      className={`relative max-w-[70%] ${bubblePadding} shadow-md ${
                        isInbound
                          ? "bg-white text-slate-900 border border-slate-200/70 rounded-xl rounded-tl-sm"
                          : "bg-[#117957] text-white border border-emerald-950/20 rounded-xl rounded-tr-sm"
                      }`}
                    >
                      <span
                        aria-hidden="true"
                        className={`absolute top-2 w-3 h-3 rotate-45 ${
                          isInbound
                            ? "left-[-5px] bg-white border-l border-b border-slate-200/70"
                            : "right-[-5px] bg-[#117957] border-r border-t border-emerald-950/20"
                        }`}
                      />
                      <div
                        className={`whitespace-pre-wrap break-words ${contentRightPad}`}
                      >
                        {(() => {
                          const mt = mtOuter;
                          const previewUrl = mediaId
                            ? msg.localPreviewUrl ||
                              mediaObjectUrlById?.[mediaId] ||
                              null
                            : null;

                          if (!hasMedia) return msg.text || "-";

                          return (
                            <div className="space-y-1">
                              {mt === "image" ? (
                                <ImageMediaTile
                                  msg={msg}
                                  isInbound={isInbound}
                                  previewUrl={previewUrl}
                                  onOpen={handleOpenMedia}
                                  ensureImagePreview={ensureImagePreview}
                                  timeText={showBottomMeta ? null : timeText}
                                  status={msg.status}
                                  showStatus={showStatus}
                                />
                              ) : mt === "document" ? (
                                <PdfMediaCard
                                  msg={msg}
                                  isInbound={isInbound}
                                  pdfMeta={
                                    mediaId ? pdfPreviewById?.[mediaId] : null
                                  }
                                  onOpen={handleOpenMedia}
                                  ensurePdfPreview={ensurePdfPreview}
                                />
                              ) : mt === "video" ? (
                                <VideoMediaTile
                                  msg={msg}
                                  isInbound={isInbound}
                                  previewUrl={previewUrl}
                                  onOpen={handleOpenMedia}
                                  ensureMediaPreview={ensureImagePreview}
                                  timeText={showBottomMeta ? null : timeText}
                                  status={msg.status}
                                  showStatus={showStatus}
                                />
                              ) : mt === "audio" ? (
                                <AudioMediaCard
                                  msg={msg}
                                  isInbound={isInbound}
                                  previewUrl={previewUrl}
                                  ensureMediaPreview={ensureImagePreview}
                                />
                              ) : mt === "location" ? (
                                <LocationCard msg={msg} isInbound={isInbound} />
                              ) : (
                                msg.text || "-"
                              )}
                              {captionText && (
                                <div className="text-[13px]">{captionText}</div>
                              )}
                            </div>
                          );
                        })()}
                      </div>
                      {showBottomMeta && (
                        <div
                          className={`absolute bottom-[2px] right-2 text-[10px] leading-none flex items-center gap-0.5 ${
                            isInbound ? "text-slate-500" : "text-white/70"
                          }`}
                        >
                          {timeText}

                          {!msg.isInbound && (
                            <StatusIcon status={msg.status} variant="onDark" />
                          )}
                        </div>
                      )}

                      {msg.errorMessage && (
                        <div className="mt-0.5 text-[10px] text-rose-200">
                          {msg.errorMessage}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}

            <div ref={messagesEndRef} />
          </div>
        )}
      </div>

      <div className="border-t border-slate-200 bg-white px-4 py-3">
        {selectedConversation && isConversationClosed && (
          <div className="text-[11px] text-rose-600 mb-2">
            This conversation is <span className="font-semibold">closed</span>.
            Reopen it to send a reply.
          </div>
        )}

        {selectedConversation && !isConversationClosed && !isWithin24h && (
          <div className="text-[11px] text-amber-600 mb-2">
            This conversation is <span className="font-semibold">outside</span>{" "}
            the 24-hour WhatsApp window. Free-form replies are disabled here.
            Use approved templates (campaigns / flows) to re-engage.
          </div>
        )}

        <div ref={composerRef} className="relative space-y-2">
          <ComposerTabs
            openTab={openTab}
            setOpenTab={setOpenTab}
            composerRef={composerRef}
            onQuickReplyInsert={text => {
              insertAtCursor(text);
            }}
          />

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => {
                setEmojiOpen(false);
                setOpenTab(prev => (prev === "quickReply" ? null : "quickReply"));
              }}
              disabled={isComposerDisabled}
              className={`h-9 inline-flex items-center gap-1.5 rounded-lg border px-3 text-[12px] font-medium ${
                isComposerDisabled
                  ? "bg-slate-50 text-slate-400 border-slate-200 cursor-not-allowed"
                  : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
              }`}
              title="Quick replies"
            >
              <Zap className="w-4 h-4" />
              Quick reply
            </button>

            <div className="relative">
              <button
                type="button"
                className={`h-9 w-9 inline-flex items-center justify-center rounded-lg border ${
                  isComposerDisabled
                    ? "bg-slate-50 text-slate-400 border-slate-200 cursor-not-allowed"
                    : "bg-white text-slate-600 border-slate-200 hover:bg-slate-50 hover:text-slate-800"
                }`}
                title="Emoji"
                disabled={isComposerDisabled}
                aria-expanded={emojiOpen}
                onClick={() => {
                  setOpenTab(null);
                  setEmojiOpen(v => !v);
                }}
              >
                <Smile className="w-4 h-4" />
              </button>

              {emojiOpen && !isComposerDisabled && (
                <div className="absolute left-0 bottom-full mb-2 z-50">
                  <EmojiPicker
                    onPick={emoji => {
                      insertAtCursor(emoji);
                      setEmojiOpen(false);
                    }}
                    onClose={() => setEmojiOpen(false)}
                  />
                </div>
              )}
            </div>

            <input
              ref={fileInputRef}
              type="file"
              accept="image/*,application/pdf,video/mp4,video/3gpp,audio/mpeg,audio/mp4,audio/aac,audio/ogg"
              className="hidden"
              onChange={e => {
                const f = e.target.files?.[0] || null;
                e.target.value = "";
                if (!f) return;
                handleUploadAndSendMedia?.(f);
              }}
            />

            <button
              type="button"
              className={`h-9 w-9 inline-flex items-center justify-center rounded-lg border ${
                isComposerDisabled
                  ? "bg-slate-50 text-slate-400 border-slate-200 cursor-not-allowed"
                  : "bg-white text-slate-600 border-slate-200 hover:bg-slate-50 hover:text-slate-800"
              }`}
              title={isComposerDisabled ? "Attach" : "Attach (image/PDF/video/audio)"}
              disabled={isComposerDisabled}
              onClick={() => fileInputRef.current?.click()}
            >
              <Paperclip className="w-4 h-4" />
            </button>

            <button
              type="button"
              className={`h-9 w-9 inline-flex items-center justify-center rounded-lg border ${
                isComposerDisabled
                  ? "bg-slate-50 text-slate-400 border-slate-200 cursor-not-allowed"
                  : "bg-white text-slate-600 border-slate-200 hover:bg-slate-50 hover:text-slate-800"
              }`}
              title={isComposerDisabled ? "Location" : "Send current location"}
              disabled={isComposerDisabled}
              onClick={() => handleSendLocation?.()}
            >
              <MapPin className="w-4 h-4" />
            </button>

            <textarea
              ref={textareaRef}
              rows={1}
              value={newMessage}
              onChange={e => setNewMessage(e.target.value)}
              onKeyDown={handleTextareaKeyDown}
              placeholder={
                selectedConversation
                  ? isConversationClosed
                    ? "Conversation is closed."
                    : isWithin24h
                    ? "Type a reply."
                    : "24h window expired - send via template campaign."
                  : "Select a conversation first."
              }
              disabled={
                !selectedConversation ||
                isConversationClosed ||
                !isWithin24h ||
                isSending ||
                isUploadingMedia
              }
              className={`flex-1 resize-none border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500 ${
                !selectedConversation || isConversationClosed || !isWithin24h
                  ? "bg-slate-50 text-slate-400 cursor-not-allowed"
                  : "bg-white"
              }`}
            />
            <button
              type="button"
              onClick={() => handleSendMessage?.()}
              disabled={
                isSending ||
                isUploadingMedia ||
                !newMessage.trim() ||
                !selectedConversation ||
                isConversationClosed ||
                !isWithin24h
              }
              className={`bg-emerald-600 text-white text-sm font-medium px-4 py-2 rounded-lg shadow-sm ${
                isSending ||
                isUploadingMedia ||
                !newMessage.trim() ||
                !selectedConversation ||
                isConversationClosed ||
                !isWithin24h
                  ? "opacity-60 cursor-not-allowed"
                  : "hover:bg-emerald-700"
              }`}
            >
              {isUploadingMedia ? "Uploading..." : isSending ? "Sending..." : "Send"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
